import Groq from "groq-sdk";

export interface InterviewQuestionRequest {
  jobRole: string;
  experienceLevel: string;
  numberOfQuestions?: number;
  previousQuestions?: string[];
}

export interface InterviewQuestion {
  question_text: string;
  category: string;
  difficulty: string;
}

export interface FeedbackAnalysis {
  overall_score: number;
  communication: string;
  knowledge: string;
  recommendations: string;
  strengths: string[];
  improvements: string[];
  detailed_feedback: {
    clarity: number;
    technical_depth: number;
    problem_solving: number;
    professionalism: number;
  };
}

/**
 * Generate interview questions using Groq (Llama 3.1 70B)
 */
export async function generateInterviewQuestions(
  request: InterviewQuestionRequest,
  apiKey: string
): Promise<InterviewQuestion[]> {
  const groq = new Groq({ apiKey });

  const prompt = `You are an expert technical interviewer. Generate ${request.numberOfQuestions || 7} interview questions for a ${request.jobRole} position at ${request.experienceLevel} level.

Requirements:
- Mix technical and behavioral questions
- Progressively increase difficulty
- Be role-specific and relevant
- Include different categories: technical, behavioral, problem-solving, situational

Return ONLY a JSON object with a "questions" array with this structure:
{
  "questions": [
    {
      "question_text": "The actual question to ask",
      "category": "technical|behavioral|problem-solving|situational",
      "difficulty": "easy|medium|hard"
    }
  ]
}

Do not include any markdown formatting or explanations. Return only valid JSON.`;

  try {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: "You are an expert technical interviewer. Always respond with valid JSON only.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 2048,
      response_format: { type: "json_object" },
    });

    const text = completion.choices[0]?.message?.content;
    
    if (!text) {
      throw new Error("No content received from Groq");
    }

    // Parse the response
    const parsed = JSON.parse(text);
    
    // Handle both array and object responses
    const questions = Array.isArray(parsed) ? parsed : parsed.questions || [];

    if (!questions || questions.length === 0) {
      console.warn("No questions generated by Groq, using fallback");
      return generateFallbackQuestions(request.jobRole, request.experienceLevel);
    }

    return questions.map((q: any) => ({
      question_text: q.question_text || q.question,
      category: q.category || "general",
      difficulty: q.difficulty || "medium",
    }));
  } catch (error) {
    console.error("Error generating questions with Groq:", error);
    
    // Fallback questions if API fails
    return generateFallbackQuestions(request.jobRole, request.experienceLevel);
  }
}

/**
 * Generate next question based on conversation context
 */
export async function generateNextQuestion(
  jobRole: string,
  conversationHistory: Array<{ role: "system" | "user" | "assistant"; content: string }>,
  apiKey: string
): Promise<string> {
  const groq = new Groq({ apiKey });

  const systemPrompt = `You are conducting a professional interview for a ${jobRole} position. Based on the conversation so far, ask the next relevant follow-up question. Be conversational and professional.`;

  const conversationText = conversationHistory
    .map(msg => `${msg.role}: ${msg.content}`)
    .join("\n");

  const prompt = `${systemPrompt}\n\nConversation so far:\n${conversationText}\n\nAsk the next relevant interview question:`;

  try {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: systemPrompt,
        },
        {
          role: "user",
          content: `Conversation so far:\n${conversationText}\n\nAsk the next relevant interview question:`,
        },
      ],
      temperature: 0.8,
      max_tokens: 256,
    });

    const text = completion.choices[0]?.message?.content;
    
    return text || "Can you tell me more about your experience?";
  } catch (error) {
    console.error("Error generating next question with Groq:", error);
    return "Can you elaborate on your previous answer?";
  }
}

/**
 * Generate comprehensive feedback using Groq (Llama 3.1 70B)
 */
export async function generateInterviewFeedback(
  transcript: Array<{ question: string; answer: string }>,
  jobRole: string,
  apiKey: string
): Promise<FeedbackAnalysis> {
  const groq = new Groq({ apiKey });

  const conversationText = transcript
    .map((item, idx) => `Q${idx + 1}: ${item.question}\nA${idx + 1}: ${item.answer}`)
    .join("\n\n");

  const prompt = `Analyze this interview for a ${jobRole} position and provide detailed feedback.

Interview Transcript:
${conversationText}

Provide a comprehensive analysis in JSON format with these exact fields:
{
  "overall_score": <number 0-100>,
  "communication": "<brief assessment>",
  "knowledge": "<brief assessment>",
  "recommendations": "<actionable advice>",
  "strengths": ["<strength 1>", "<strength 2>", "<strength 3>"],
  "improvements": ["<improvement 1>", "<improvement 2>", "<improvement 3>"],
  "detailed_feedback": {
    "clarity": <number 0-100>,
    "technical_depth": <number 0-100>,
    "problem_solving": <number 0-100>,
    "professionalism": <number 0-100>
  }
}

Return ONLY valid JSON without markdown formatting.`;

  try {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: "You are an expert interview evaluator. Always respond with valid JSON only.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 2048,
      response_format: { type: "json_object" },
    });

    const text = completion.choices[0]?.message?.content;
    
    if (!text) {
      throw new Error("No feedback generated");
    }

    const feedback = JSON.parse(text);
    
    return {
      overall_score: feedback.overall_score || 75,
      communication: feedback.communication || "Good communication skills demonstrated",
      knowledge: feedback.knowledge || "Adequate technical knowledge shown",
      recommendations: feedback.recommendations || "Continue practicing interview skills",
      strengths: feedback.strengths || ["Clear communication", "Professional demeanor"],
      improvements: feedback.improvements || ["Provide more detailed examples"],
      detailed_feedback: feedback.detailed_feedback || {
        clarity: 75,
        technical_depth: 70,
        problem_solving: 72,
        professionalism: 80,
      },
    };
  } catch (error) {
    console.error("Error generating feedback with Groq:", error);
    
    // Return generic feedback if API fails
    return {
      overall_score: 75,
      communication: "Interview completed successfully",
      knowledge: "Demonstrated relevant knowledge",
      recommendations: "Continue developing your interview skills",
      strengths: ["Completed the interview", "Engaged with questions"],
      improvements: ["Practice providing more detailed responses"],
      detailed_feedback: {
        clarity: 75,
        technical_depth: 70,
        problem_solving: 72,
        professionalism: 80,
      },
    };
  }
}

/**
 * Fallback questions when API is unavailable
 */
function generateFallbackQuestions(jobRole: string, experienceLevel: string): InterviewQuestion[] {
  const baseQuestions: InterviewQuestion[] = [
    {
      question_text: `Tell me about your background and experience relevant to ${jobRole}.`,
      category: "behavioral",
      difficulty: "easy",
    },
    {
      question_text: "What are your greatest technical strengths?",
      category: "technical",
      difficulty: "easy",
    },
    {
      question_text: "Describe a challenging project you worked on and how you overcame obstacles.",
      category: "behavioral",
      difficulty: "medium",
    },
    {
      question_text: "How do you stay updated with industry trends and new technologies?",
      category: "behavioral",
      difficulty: "easy",
    },
    {
      question_text: "Walk me through your problem-solving approach when facing a complex technical issue.",
      category: "problem-solving",
      difficulty: "medium",
    },
    {
      question_text: "Tell me about a time you had to work with a difficult team member.",
      category: "situational",
      difficulty: "medium",
    },
    {
      question_text: "Where do you see yourself in your career in the next 3-5 years?",
      category: "behavioral",
      difficulty: "easy",
    },
  ];

  return baseQuestions;
}
